# Generated by Django 2.0.3 on 2018-03-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gomim', models.IntegerField(help_text='Gene omim id')),
                ('pomim', models.IntegerField(help_text='disease omim id')),
                ('phenotype', models.CharField(help_text='disease phenotype description', max_length=255)),
                ('symbol', models.CharField(help_text='disease phenotype symbol', max_length=20)),
                ('orthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macaca.Orthology')),
            ],
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(db_index=True, help_text='drugbank durg id', max_length=7),
        ),
        migrations.AlterField(
            model_name='function',
            name='source',
            field=models.IntegerField(choices=[(1, 'GO'), (2, 'KEGG'), (3, 'Pfam'), (4, 'InterPro')], db_index=True, help_text='The function source database name'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='feature',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='genotype',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='mutation',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='drug',
            index_together={('drug_id', 'orthology')},
        ),
        migrations.AlterIndexTogether(
            name='statistics',
            index_together={('feature', 'genotype', 'mutation')},
        ),
    ]
