# Generated by Django 2.0.3 on 2018-03-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.IntegerField()),
                ('genotype', models.IntegerField()),
                ('mutation', models.IntegerField()),
                ('counts', models.IntegerField()),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macaca.Chromosome')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macaca.Individual')),
            ],
        ),
    ]
