# Generated by Django 2.0 on 2018-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='synonymous',
            field=models.IntegerField(choices=[(1, 'Synonymous'), (2, 'Non-synonymous')], db_index=True, help_text='Mutation type'),
        ),
        migrations.AlterField(
            model_name='tannot',
            name='synonymous',
            field=models.IntegerField(choices=[(1, 'Synonymous'), (2, 'Non-synonymous')], db_index=True, help_text='Mutation type'),
        ),
    ]
