# Generated by Django 2.0.3 on 2018-05-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='code',
            field=models.CharField(default='', help_text='New code', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='mapkey',
            field=models.PositiveSmallIntegerField(choices=[(1, 'The disorder was positioned by mapping of the wildtype gene'), (2, 'The disease phenotype itself was mapped'), (3, 'The molecular basis of the disorder is known'), (4, 'The disorder is a chromosome deletion or duplication syndrome')], help_text='Phenotype mapping key'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'biotech'), (2, 'small molecule')], help_text='drugbank drug type'),
        ),
        migrations.AlterField(
            model_name='function',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GO'), (2, 'KEGG'), (3, 'Pfam'), (4, 'InterPro')], db_index=True, help_text='The function source database name'),
        ),
        migrations.AlterField(
            model_name='gannot',
            name='feature',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CDS'), (2, 'Exon'), (3, "3'UTR"), (4, 'Intron'), (5, "5'UTR")], db_index=True, help_text='Gene features'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='biotype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'protein coding'), (2, 'pseudogene'), (3, 'snRNA'), (4, 'rRNA'), (5, 'miRNA'), (6, 'miscRNA'), (7, 'snoRNA')], help_text='Gene coding types'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='synonymous',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Synonymous'), (2, 'Non-synonymous')], db_index=True, help_text='Mutation type'),
        ),
        migrations.AlterField(
            model_name='tannot',
            name='synonymous',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Synonymous'), (2, 'Non-synonymous')], db_index=True, help_text='Mutation type'),
        ),
    ]
