# Generated by Django 2.0 on 2018-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0002_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='ensembl',
            field=models.CharField(db_index=True, help_text='Ensembl gene id', max_length=18),
        ),
    ]
