# Generated by Django 2.0.3 on 2018-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0002_auto_20180506_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symbol',
        ),
        migrations.AddField(
            model_name='disease',
            name='inheritance',
            field=models.CharField(default='', help_text='Inheritance', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='mapkey',
            field=models.SmallIntegerField(choices=[(1, 'The disorder was positioned by mapping of the wildtype gene'), (2, 'The disease phenotype itself was mapped'), (3, 'The molecular basis of the disorder is known'), (4, 'The disorder is a chromosome deletion or duplication syndrome')], default=1, help_text='Phenotype mapping key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='gomim',
            field=models.IntegerField(help_text='gene omim accession'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pomim',
            field=models.IntegerField(db_index=True, help_text='disease omim accession'),
        ),
    ]
