# Generated by Django 6.0.4 on 2026-04-25 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('approve_code', models.CharField(blank=True, max_length=50)),
                ('finance_code', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('approve_amount', models.FloatField(default=0)),
                ('approve_time', models.DateField(blank=True)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dulab/files/%Y/%m')),
                ('ctype', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('content_zh', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='dulab/thumbnails')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=100)),
                ('year', models.SmallIntegerField()),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('issue', models.CharField(blank=True, max_length=10)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('doi', models.CharField(max_length=100)),
                ('pmid', models.CharField(blank=True, max_length=30)),
                ('factor', models.FloatField(blank=True, default=0)),
                ('cover', models.ImageField(blank=True, upload_to='dulab/thumbnails/')),
                ('pdf', models.FileField(blank=True, upload_to='dulab/papers/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_zh', models.TextField()),
                ('direction_en', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='dulab/thumbnails/')),
                ('rank', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_zh', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slide', models.ImageField(upload_to='dulab/slides/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('extra_zh', models.TextField(blank=True)),
                ('extra_en', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('doc', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('category', models.SmallIntegerField(choices=[(1, '软件'), (2, '数据库')], default=0)),
                ('comment_zh', models.TextField(blank=True)),
                ('comment_en', models.TextField(blank=True)),
                ('description_zh', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='dulab/thumbnails/')),
                ('logo', models.ImageField(blank=True, upload_to='dulab/thumbnails/')),
                ('citation', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, '其他费'), (1, '材料费'), (2, '测序费'), (3, '设备费'), (4, '劳务费'), (5, '差旅费'), (6, '版面费'), (7, '咨询费'), (8, '绩效'), (9, '管理费'), (10, '税费')], default=0)),
                ('amount', models.FloatField()),
                ('company', models.CharField(blank=True, max_length=255)),
                ('invoice', models.FileField(blank=True, upload_to='dulab/invoices/%Y/%m')),
                ('ticket', models.FileField(blank=True, upload_to='dulab/tickets/%Y/%m')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulab.fund')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(blank=True, max_length=30)),
                ('name_en', models.CharField(blank=True, max_length=30)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('qq', models.CharField(blank=True, max_length=20)),
                ('weixin', models.CharField(blank=True, max_length=30)),
                ('major_zh', models.CharField(blank=True, max_length=30)),
                ('major_en', models.CharField(blank=True, max_length=50)),
                ('grade', models.IntegerField(blank=True, choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2020)),
                ('degree', models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0)),
                ('position', models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '研究生'), (2, '本科生'), (3, '博士后'), (4, '教职工'), (5, '访问学者')], default=0)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '在读'), (2, '毕业'), (3, '退学')], default=0)),
                ('direct_zh', models.CharField(blank=True, max_length=255)),
                ('direct_en', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='dulab/avatars/')),
                ('bio_zh', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('researchgate', models.CharField(blank=True, max_length=255)),
                ('google', models.CharField(blank=True, max_length=255)),
                ('allowed', models.SmallIntegerField(blank=True, choices=[(0, '待审'), (1, '通过')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['degree', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title_zh', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('content_zh', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='dulab/thumbnails/')),
                ('banner', models.ImageField(blank=True, upload_to='dulab/banners/')),
                ('approve', models.SmallIntegerField(choices=[(0, '等待审核'), (1, '通过审核'), (2, '退回修改')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulab.member')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('changelog_zh', models.TextField(blank=True)),
                ('changelog_en', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulab.software')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Windows'), (2, 'MacOS'), (3, 'Linux'), (4, 'Ubuntu'), (5, 'Fedora'), (6, 'Debian'), (7, 'RedHat'), (8, 'ArchLinux'), (9, 'openSUSE'), (10, 'AlmaLinux'), (11, 'Deepin'), (12, 'Centos'), (13, 'RockyLinux')], default=0)),
                ('comment_zh', models.CharField(blank=True, max_length=255)),
                ('comment_en', models.CharField(blank=True, max_length=255)),
                ('package', models.FileField(upload_to='dulab/files/%Y/%m')),
                ('represent', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulab.version')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
    ]
