# Generated by Django 6.0.4 on 2026-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
