# Generated by Django 6.0.4 on 2026-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0002_remove_option_name_option_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='slide',
            field=models.FileField(upload_to='dulab/slides/'),
        ),
    ]
