# Generated by Django 6.0.4 on 2026-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0003_alter_slideshow_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
