# Generated by Django 6.0.4 on 2026-04-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0005_remove_member_email_remove_member_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='个人简介(英文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio_zh',
            field=models.TextField(blank=True, verbose_name='个人简介(中文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='direct_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='研究方向(英文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='direct_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='研究方向(中文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2020, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='member',
            name='major_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='专业(英文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='major_zh',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业(中文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name_zh',
            field=models.CharField(blank=True, max_length=30, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '研究生'), (2, '本科生'), (3, '博士后'), (4, '教职工'), (5, '访问学者')], default=0, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qq',
            field=models.CharField(blank=True, max_length=20, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未设置'), (1, '在读'), (2, '毕业'), (3, '退学')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='头衔(英文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='头衔(中文)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weixin',
            field=models.CharField(blank=True, max_length=30, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, upload_to='dulab/banners/', verbose_name='Banner图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='内容(英文)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_zh',
            field=models.TextField(blank=True, verbose_name='内容(中文)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='文章英文缩写名', unique=True, verbose_name='文章缩写名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='dulab/thumbnails/', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='标题(英文)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_zh',
            field=models.CharField(max_length=255, verbose_name='标题(中文)'),
        ),
    ]
