# Generated by Django 6.0.4 on 2026-05-10 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0006_alter_member_bio_en_alter_member_bio_zh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.CharField(blank=True, max_length=30, verbose_name='学号或工号'),
        ),
        migrations.AddField(
            model_name='software',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='software',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2020, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, upload_to='dulab/banners/%Y/%m', verbose_name='Banner图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='dulab/thumbnails/%Y/%m', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='research',
            name='thumbnail',
            field=models.ImageField(upload_to='dulab/thumbnails/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='slide',
            field=models.FileField(upload_to='dulab/slides/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='software',
            name='logo',
            field=models.ImageField(blank=True, upload_to='dulab/thumbnails/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='software',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='dulab/thumbnails/%Y/%m'),
        ),
    ]
