# Generated by Django 6.0.4 on 2026-05-08 02:24

import wangeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0007_alter_member_grade_alter_post_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=wangeditor.fields.WangRichTextField(blank=True, verbose_name='内容(英文)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_zh',
            field=wangeditor.fields.WangRichTextField(blank=True, verbose_name='内容(中文)'),
        ),
    ]
