# Generated by Django 6.0.4 on 2026-05-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0008_alter_software_citation_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-uploaded', 'system']},
        ),
        migrations.AddField(
            model_name='download',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='download',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='dulab.version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dulab.software'),
        ),
    ]
