# Generated by Django 6.0.4 on 2026-05-08 02:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0008_alter_post_content_en_alter_post_content_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='内容(英文)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_zh',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='内容(中文)'),
        ),
    ]
