# Generated by Django 6.0.4 on 2026-05-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0009_alter_download_options_download_visitor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
