# Generated by Django 6.0.4 on 2026-05-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0010_download_name_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-uploaded', '-system']},
        ),
    ]
