# Generated by Django 6.0.4 on 2026-05-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0011_alter_download_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AlterField(
            model_name='member',
            name='allowed',
            field=models.SmallIntegerField(choices=[(0, '待审'), (1, '通过')], default=0, verbose_name='资格审查'),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.SmallIntegerField(choices=[(0, '未设置'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2020, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.SmallIntegerField(choices=[(0, '未设置'), (1, '教授'), (2, '访问学者'), (3, '博士后'), (4, '研究生'), (5, '本科生'), (6, '助理研究员'), (7, '教职员')], default=0, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未设置'), (1, '在读'), (2, '毕业'), (3, '退学')], default=0, verbose_name='状态'),
        ),
    ]
