# Generated by Django 6.0.4 on 2026-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0012_alter_download_options_alter_member_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.SmallIntegerField(choices=[(0, '未设置'), (1, '教职工'), (2, '访问学者'), (3, '博士后'), (4, '研究生'), (5, '本科生')], default=0, verbose_name='职位'),
        ),
    ]
