# Generated by Django 6.0.4 on 2026-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0013_alter_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='comment_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='version',
            name='comment_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='system',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Windows'), (2, 'MacOS'), (3, 'Linux')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.SmallIntegerField(choices=[(0, '未设置'), (1, '教授'), (2, '研究员'), (3, '副教授'), (4, '副研究员'), (5, '讲师'), (6, '助理研究员'), (7, '教职员'), (8, '访问学者'), (9, '博士后'), (10, '研究生'), (11, '本科生')], default=0, verbose_name='职位'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
