# Generated by Django 6.0.4 on 2026-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulab', '0014_version_comment_en_version_comment_zh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='member',
            name='identity',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '教职工'), (2, '研究生'), (3, '本科生')], default=0, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='member',
            name='allowed',
            field=models.SmallIntegerField(choices=[(0, '待审'), (1, '通过'), (2, '锁定')], default=0, verbose_name='资格审查'),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '教授'), (2, '研究员'), (3, '副教授'), (4, '副研究员'), (5, '讲师'), (6, '助理研究员'), (7, '访问学者'), (8, '博士后')], default=0, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '在读'), (2, '毕业'), (3, '退学'), (4, '在职'), (5, '离职')], default=0, verbose_name='状态'),
        ),
    ]
