# Generated by Django 2.0 on 2018-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
