# Generated by Django 2.0 on 2018-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0003_auto_20180513_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.SmallIntegerField(default=2018),
            preserve_default=False,
        ),
    ]
